version: '3'

services:
  db:
    image: "sameersbn/postgresql:9.6-2"
    container_name: reports_db_v2
    hostname: reports_db_v2
    restart: always
    env_file:
      - ./docker/environments
    volumes:
      - ./pg_data:/var/lib/postgresql/9.6/main
    ports:
      - "5432:5432"
  api:
    build: ./api
    container_name: ddc_api
    hostname: ddc_api
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"
    env_file:
      - ./docker/environments
    depends_on:
      - db
  frontend:
    build: ./frontend
    container_name: ddc_frontend
    hostname: ddc_frontend
    ports:
      - "3000:3000"
    env_file:
      - ./docker/environments
    depends_on:
      - api
