version: '3'
services:
  insake_accounts_service:
    build: .
    restart: always
    external_links:
      - insakeauthservice_insake_auth_service_1
    networks:
      - default
      - insakeauthservice_default
    links:
      - accounts_database
    ports:
      - "3002:3000"
    environment:
      ACCOUNTS_SERVICE_LOCAL_ENV: "local"
      ACCOUNTS_SERVICE_LOCAL_DATABASE_DIALECT: "postgres"
      ACCOUNTS_SERVICE_LOCAL_DATABASE_HOST: "accounts_database"
      ACCOUNTS_SERVICE_LOCAL_DATABASE_PASSWORD: "${POSTGRES_PASSWORD}"
      ACCOUNTS_SERVICE_LOCAL_DATABASE_USER: "${POSTGRES_USER}"
      ACCOUNTS_SERVICE_LOCAL_DATABASE_DB: "${POSTGRES_DB}"
  accounts_database:
    image: postgres
    restart: always
    networks:
      - default
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
  insake_accounts_doc:
    build: doc
    ports:
      - 6060:8080
networks:
  insakeauthservice_default:
    external: true
